### PR TITLE
Remove duplicate word

### PR DESCRIPTION
**Pull request by sapegin**

### CODE REVIEW

**Comment by mrsteele** [comment]
Haha, hilarious / embarrassing! I'm not an English major 🤣

**Comment by mrsteele** [comment]
thanks @sapegin

**Comment by sapegin** [comment]
@mrsteele Actually I’m a bit unsure about this sentence ;-) What exactly “overwrites any existing DefinePlugin” means? Does it mean that this plugin can’t be used with DefinePlugin?

**Comment by mrsteele** [comment]
@sapegin So it used to be the case that this plugin was not compatible with DefinePlugin. It appears at some point it became compatible. So that sentence might be void at this point.

**Comment by sapegin** [comment]
I don’t see anything that suggest that you can’t use DefinePlugin multiple times in their docs except:

> When defining values for process prefer 'process.env.NODE_ENV': JSON.stringify('production') over process: { env: { NODE_ENV: JSON.stringify('production') } }. Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined.

**Comment by mrsteele** [comment]
Yeah we are probably good to remove that DefinePluggin bit 😉

**Pull request merged**
