### PR TITLE
feat: supporting webpack 5

### LINKED ISSUE #184: Does this work with Webpack 5?
Getting some strange behavior on Webpack 5, still debugging, but I'd like to know if this is possible to use with it.

### PR DESCRIPTION
**Pull request by mrsteele**
Closes #184 as well as some other artifact issues I was seeing.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Hey, just a quick question, when is this expected to land?
Is there anything holding this off?

I would like to build on it, and since we're using dotenv-webpack in our project that's a blocker for me right now.

**Comment by mrsteele** [comment]
@MarcelGerber Haha I'm kinda waiting for someone like you to tell me they need it. Normally a little hesitant to update so I'll update all those dependencies then try and get this in.

**Comment by MarcelGerber** [comment]
@mrsteele Great, and thank you so much for the effort you're putting in here. Greatly appreciated!

**Pull request merged**
