### PR TITLE
webpack should be direct dependency

### PR DESCRIPTION
**Pull request by rashidul0405**
lerna couldn't resolve webpack dependency.

We've lerna.js setup.
- A project use webpack@4.
- Another project use webpack@3
When we run dotenv-webpack from webpack@3 project's scope, it always resolves to webpack@4 as webpack@4 is on the global scope.

### CODE REVIEW

**Comment by rashidul0405** [comment]
we are using version 1.5.4 due to compatibility with webpack@3, can this fix be included with 1.5.4 release, please?

**Comment by rashidul0405** [comment]
travis-ci build disabled: `Build type disabled via repository settings (pull_request).`

**Comment by mrsteele** [comment]
@rashidul0405 Thanks for the PR, however I am a little confused.

We have a "dev" dependency on our personal development to include webpack for the purposes of our unit testing. So in your environment you shouldn't need the dev dependency.

We also have the peer dependency here: https://github.com/mrsteele/dotenv-webpack/pull/137/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R42

This should satisfy the conflicting dependency issue you see as they are both covered.

**Comment by rashidul0405** [comment]
@mrsteele Thank you very much for your reply. It could be related to https://github.com/lerna/lerna. I'll explore more and will get back to you.

**Comment by mrsteele** [comment]
I'm going to close this as I think this has gone stale, but if you think it should be reopened/reconsidered, feel free to reopen.

**Pull request closed without merging**
