### PR TITLE
feat: support for additional variables

### PR DESCRIPTION
**Pull request by supercycle91**
Proposed support for additional variables outside of .env file. This feature is intended for things like VERSION from package.json or something that is more dynamic. 
`new Dotenv({
			path: './.env',
			additionalVars: {
				VERSION: JSON.stringify(require('./package.json').version)
			}
		})
`
EXAMPLE
`console.log(VERSION)//1.0.0`

### CODE REVIEW

**Comment by mrsteele** [comment]
Hey @supercycle91 and thanks for the PR.

Would you mind explaining a use-case that couldn't be solved by using `webpack.DefinePlugin` alongside `dotenv-webpack`?

i.e. Your proposed solution above can be resolved by using the following config in your plugins prop:

```javascript
plugins: [
    // new webpack.NoEmitOnErrorsPlugin(),
    new Dotenv({
      path: '.env' // this is the default so you can actually exclude it if you want
    }),
    new webpack.DefinePlugin({
      'process.env.VERSION': JSON.stringify(require('./package.json').version)
    })
  ],
```

**Comment by supercycle91** [comment]
@mrsteele My thought process was just packaging them together since Dotenv is already wrapping webpack.DefinePlugin. I was surprised when I started using your library that I could not pass any additional variables outside the dot-env. The ability to add additional non process.env variables without an additional webpack.DefinePlugin instance makes more sense with me.

**Comment by supercycle91** [comment]
@mrsteele Any update on this?

**Comment by mrsteele** [comment]
I'm waiting to see others interest. As it stands I would still argue that this request is superfluous, but if others agree that this is needed then I would reconsider.

**Pull request closed without merging**
