### PR TITLE
feat(constructor): expose 'failSoftly' (=catch load error) option

### PR DESCRIPTION
**Pull request by cbrunnkvist**
I need my build to fail in case opening the `.env` file fails. This patch adds an option `failSoftly=true` which keeps compatibility with current behavior but allows for any exception raised in .parse() to propagate when set to `false`.

### CODE REVIEW

**Comment by mrsteele** [comment]
Thanks for the contribution @cbrunnkvist!

I'm trying to chew on this a bit because I'm wondering now if we should be forcing a failed parse all the time.

If the file doesn't exist, I think we should let that work as is, however a PARSE error is much different and perhaps we should be forwarding that.

What do you think about updating it to not have that configuration option but instead check for the **type** of error.

If the error is because the file is missing, do what currently happens in prod, if the error is a parsing error, throw that error as expected.

Thoughts?

**Comment by cbrunnkvist** [comment]
Surprised to see CI failing, I was working for me... 

Regarding failing on different types of errors: doing that is a possibility, once you bump up a minor version. My idea was to keep this as a _patch_ i.e. without breaking backwards compatibility, at least to start with. There's nothing that says you can't do both though (e.g. add option for _M.m.[p+1]_, start throwing stuff in _M.[m+1].0_).

For my use-case though, I need it to be able to _fail_ when the file is missing _or_ any other issue with it.

**Comment by cbrunnkvist** [comment]
(Oh, the build failure is just because `CODECLIMATE_REPO_TOKEN` is missing -> unless you manage to get access to the secret token during PR builds, I would separate that step out to a separate build)

**Comment by mrsteele** [comment]
I hear everything you are saying @cbrunnkvist but I also am challenged by this due to the fact that `dotenv` doesn't do this (or does it? I couldn't find anything in their docs that state this).

This could also be resolved as a build step validation to determine first if the file is set. I think that would solve your problem but I also want to make sure this is a problem others have run into. This is a good use case you stated above but also not sure if it needs to be `dotenv-webpack`s responsibility.

**Comment by mrsteele** [comment]
@cbrunnkvist what do you think about using the `dotenv-safe` features to help failing if missing something and setting something like `NODE_ENV` which is universally used?

**Comment by FDiskas** [comment]
Then env is missing it should always fail and ci should stop i think ,🙄

**Comment by mrsteele** [comment]
Closing due to lack of participation.

Feel free to reopen this if you still think this is pertinent, thanks.

**Pull request closed without merging**
